// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSn3pSlCbnM-3lNkBti-8qxBS3pX7aGY',
    appId: '1:832733254153:web:3f6828e0781e5d51ec1ed8',
    messagingSenderId: '832733254153',
    projectId: 'urbansightmacathon',
    authDomain: 'urbansightmacathon.firebaseapp.com',
    storageBucket: 'urbansightmacathon.firebasestorage.app',
    measurementId: 'G-W8X1S4FCE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlthrgeVXdVetL_cmqBleWCuKojAp-YI',
    appId: '1:832733254153:android:9adf45279f81fef9ec1ed8',
    messagingSenderId: '832733254153',
    projectId: 'urbansightmacathon',
    storageBucket: 'urbansightmacathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpOKK5XTufrzAr4_8NUu9eiXrMQoPXzc',
    appId: '1:832733254153:ios:02f78a7ddca09212ec1ed8',
    messagingSenderId: '832733254153',
    projectId: 'urbansightmacathon',
    storageBucket: 'urbansightmacathon.firebasestorage.app',
    iosBundleId: 'com.example.urbansight',
  );
}
